### ISSUE TITLE
CROMU_00038 Not supposed to be here

### ISSUE THREAD

**Issue by chaws** [trailofbits/cb-multios#44]
In here: https://github.com/trailofbits/cb-multios/tree/master/challenges/String_Storage_and_Retrieval, the folder CROMU_00038 is inside for no apparent reason. I check it out and CROMU_00038 and CROMU_00024 (challenge on the link) and both say "String Storage and Retrieval"

**Comment by m3lixir** [comment]
Both CROMU_00024 (String_Storage_and_Retrieval) and CROMU_00038 were CQE challenges. At commit 8360653e528325a24d0509ed600e34d9db11569c these challenges were separate, but in the following commit, ee5a6e4145f81a992e18dc477358123412e586a3, they were merged together. Both of their READMEs had the title "String Storage and Retrieval" at the time. However I assume CROMU_00038 was mistitled as it has nothing to do with string storage and retrieval (see its description).

I suggest moving CROMU_00038 to disabled-challenges in the meantime.

**Comment by woodruffw** [comment]
SGTM! Thanks for the detailed explanation.
