### ISSUE TITLE
Issues when ./build.sh with afl-clang

### ISSUE THREAD

**Issue by stuartly** [trailofbits/cb-multios#45]
[100%] Built target Casino_Games_pov_3
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: i386-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/pov-f62828.c
clang: note: diagnostic msg: /tmp/pov-f62828.sh
clang: note: diagnostic msg: 

********************
challenges/Carbonate/CMakeFiles/Carbonate_pov_1.dir/build.make:62: recipe for target 'challenges/Carbonate/CMakeFiles/Carbonate_pov_1.dir/pov_1/pov.c.o' failed
make[2]: *** [challenges/Carbonate/CMakeFiles/Carbonate_pov_1.dir/pov_1/pov.c.o] Error 254
CMakeFiles/Makefile2:516: recipe for target 'challenges/Carbonate/CMakeFiles/Carbonate_pov_1.dir/all' failed

**Comment by thuanpv** [comment]
Hi All
I face the same problem when using afl-clang-fast of afl 2.52b on Ubuntu 16.04. My clang version is 3.8. Has anyone successfully solved this problem?
Thanks

**Comment by woodruffw** [comment]
This is caused by memory exhaustion. Make sure that your machine (or VM) has enough RAM (16GB seems to work for me).

Alternatively, you can skip building the offending challenge (`Casino_Games`).
