### ISSUE TITLE
How to bulid staticlly linked and stripped file?

### ISSUE THREAD

**Issue by SiameseJuly** [trailofbits/cb-multios#59]
Here's what my CMakeLists.txt file looks like: 
~/cb-multios/CMakeLists.txt
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -z execstack -z norelro -static-libgcc -static-libstdc++")
    set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -s")
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -s")

but it doesn't work

**Comment by ekilmer** [comment]
For static linking, you can use the `build.sh` script and set the `LINK` environment variable as follows:

```
LINK=STATIC ./build.sh
```

which sets these lines https://github.com/trailofbits/cb-multios/blob/e50a0301c795c018686973d38ebcc1920f63240a/build.sh#L31-L35

However, after trying this, I ran into an issue where the CMake is trying to build `.so` files, so I opened a PR #60 with a fix. Would you be able to test that?

As for stripped files, I am unaware of any logic or code to strip the binaries of symbols after they are built, so this might need to be scripted or even better opening a PR to be added as an option, similar to building static or dynamic libraries.
