### ISSUE TITLE
Use ninja on Windows CI

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/cb-multios#65]
#64 makes macOS use ninja; Windows should do the same on AppVeyor.

**Comment by ekilmer** [comment]
I believe Windows already uses Ninja for at least the `clang` build here 
https://github.com/trailofbits/cb-multios/blob/561f2369e20e2727376028578631a7363ef9d2be/.appveyor.yml#L26-L30

**Comment by ekilmer** [comment]
Admittedly, it _only_ uses Ninja for the `clang` build https://github.com/trailofbits/cb-multios/blob/561f2369e20e2727376028578631a7363ef9d2be/build.ps1#L39-L43 

However, it uses the default CMake generator for the (broken) MSVC compiler build

**Comment by woodruffw** [comment]
Yep, my bad. I was looking at the AppVeyor scrollback and didn't see "Ninja", so I assumed it was using the default backend.
