### ISSUE TITLE
AFL-friendly CGC challenges

### ISSUE THREAD

**Issue by prashast** [trailofbits/cb-multios#70]
Hey, I don't know what is the best place to ask this so hopefully I can get some feedback here. I wanted to pick out some CGC binaries from your corpus that are ideally plug and play with AFL. By plug and play I mean they should terminate upon processing a input instead of implementing an event loop and take in as argument a single input.

 I've gone through some of them but the ones that I have analyzed are either too complex to setup with AFL or require modifications to the source code to break the event loop eg. lazy calc. I know I can do the source code modifications to such to make them AFL-friendly but I was wondering if there were any that can be plugged into AFL without any modifications.

**Comment by woodruffw** [comment]
Hey! Could you elaborate on what you mean by "too complex to setup with AFL"?

Some of the challenges are complex, but most of them interact with `stdin` in a way that AFL shouldn't struggle with. `Barcode` is a decent example of this: https://github.com/trailofbits/cb-multios/blob/fd6bf3d42a25119e77d0bf7dde6e941442c2827f/challenges/Barcoder/src/main.c#L220

**Comment by prashast** [comment]
Yeah, after playing around with the binaries a bit, I think I understand how AFL integrates seamlessly. The key point being all communication with the user being over stdin. Thanks for answering!

**Comment by woodruffw** [comment]
No problem. Best of luck with your experiments!
