### ISSUE TITLE
Sugestion - Disable jump tables on switch-case instructions

### ISSUE THREAD

**Issue by icemonster** [trailofbits/cb-multios#71]
Some switch-case instructions in DARPA challenges are compiled into efficient jump tables. That has an unfortunate downside of complicating symbolic execution since jump tables are basically indirect jumps on symbolic variables (and it's hard to know all possible jumps).

Building CFG's with tools like BAP when that kind of primitives are in the binary also fails sometimes.
Consider maybe adding the flag -fno-jump-tables to GCC which disables jump tables on switches.

**Comment by woodruffw** [comment]
Hey there!

Part of the challenge binaries being "challenges" is that they contain things like jump tables. 

We'd welcome a PR that allows for optionally disabling jump tables on switches, but the default build will continue to contain them enabled.
