### ISSUE TITLE
Cannot build in 32-bit mode

### ISSUE THREAD

**Issue by halsalem** [trailofbits/cb-multios#88]
Hi I have this error while trying to rub build.sh on linux. How can fix it?

Creating Makefiles
Creating build directory
CMake Error at cmake/32.cmake:20 (add_compile_definitions):
Unknown CMake command "add_compile_definitions".
Call Stack (most recent call first):
/usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:91 (include)
CMakeLists.txt:4 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

**Comment by halsalem** [comment]
@DarkaMaul

**Comment by woodruffw** [comment]
That error looks unrelated to anything that @DarkaMaul did. Are you running on a host that doesn't have `make` installed, or doesn't have a reasonable compiler toolchain?

**Comment by ReversingWithMe** [comment]
This is due to 3.10 vs 3.12 on Cmake, the dependency needs to be updated
