### ISSUE TITLE
Prefix all symbols with `cgc_`

### ISSUE THREAD

**Issue by withzombies** [trailofbits/cb-multios#9]
Unfortunately, the challenge creators used a lot of symbols that conflict with libc symbols (function, type, and structure names). Additionally, the type signatures were not kept consistent. This confuses static analysis tools that have encoded ISO standard C functions into their model, requiring a lot of gymnastics to get the tools working properly.

Prefixing all symbols with `cgc_` will also allow us to remove -nostdinc and make porting to Windows much more straight-forward.

**Comment by krx** [comment]
Just a note about -nostdinc, back when I was doing the namespace idea I found that anything like `#include <stdlib.h>` would include the system header instead of the one in `lib/`. So at least for building, -nostdinc makes sure the correct files are included.

**Comment by withzombies** [comment]
Yeah, those would have to be re-written too. It's more important to get these to be regular and easy-to-use test cases.
