### ISSUE TITLE
AFL test 

### ISSUE THREAD

**Issue by xia15** [trailofbits/cb-multios#92]
Hello, I am a newbie to cgc, and would like to ask me how to use AFL to test CGC. I need to use AFL's llvm mode to compile the CGC source code and test it. I have not found a tutorial on related operations at present, and I hope to get your support. Looking forward to your reply

**Comment by woodruffw** [comment]
Hi @xia15! I'd recommend asking about this in the Empire Hacking slack, particularly in the `#challenge-sets` channel. People who are actively using this repository tend to idle in this channel, and might have some advice for your use case.

Here's an invitation link to the Slack: https://empireslacking.herokuapp.com/

**Comment by xia15** [comment]
Hello, I cannot join the #challenge-sets channel through the connection you gave. Is there any other solution
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "trailofbits/cb-multios"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [trailofbits/cb-multios] AFL test  (Issue #92)





 
Hi @xia15! I'd recommend asking about this in the Empire Hacking slack, particularly in the #challenge-sets channel. People who are actively using this repository tend to idle in this channel, and might have some advice for your use case.
 
Here's an invitation link to the Slack: https://empireslacking.herokuapp.com/
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
