### ISSUE TITLE
get the error when execute ./test.py -a -o out.xlsx

### ISSUE THREAD

**Issue by Ricardio609** [trailofbits/cb-multios#93]
https://github.com/trailofbits/cb-multios/blob/6e00ce8341b239e2ef59cc02473cd74024d8571c/tools/tester.py#L86
![image](https://user-images.githubusercontent.com/64991294/144417735-1cb03193-d867-462d-8c54-def0b20a5de6.png)
It's python2 by default ? 
when I chagede from `print output` to `print(output)`, it happened:
![image](https://user-images.githubusercontent.com/64991294/144418147-2d9c00d6-1791-4022-8f59-20510670a4dc.png)
what I should handle the question?thanks

**Comment by woodruffw** [comment]
Yes, it uses Python 2. `thread` is the low-level threading module from Python 2; you can't `pip install` it.
